import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
page.on('pageerror', error => console.log('PAGE ERROR:', error.message));
await page.goto('http://localhost:5174');
await new Promise(r => setTimeout(r, 2000));
const body = await page.evaluate(() => document.body.innerText);
console.log('BODY:', body);
await browser.close();
